SEO | настройка meta тегов для страниц категорий
feya-bilyzna/development pull request #3
Opened 2022-08-05 14:21 UTC by AlecCross

2022-08-05 14:42 UTC, lifearoundfreaks requested changes

2022-08-05 14:42 UTC, lifearoundfreaks commented on src/components/VisualElements/ProductCategoryPage.jsx
> +        <MetaTags {...metaTagsData[category.route.substring(1)]}/>
Роут может быть каким угодно и не обязательно будет совпадать в будущем с ключем категории.

2022-08-05 14:42 UTC, lifearoundfreaks commented on src/data/metaTagsData.js
> +const brandsKeywords = categoriesData.categories.brands.subcategories.map(subcategory => subcategory.name).join()
Во-первых, .join() без аргументов соединит слова через запятые без пробела, возможно это будет некорректно.
Во-вторых, непонятно, как в дальнейшем переводить програмно генерируемые строки. Лучше здесь хранить массивы с названиями субкатегорий, а join делать уже в самой компоненте, тогда их там можно будет переводить.

2022-08-05 14:42 UTC, lifearoundfreaks commented on src/data/metaTagsData.js
> +        canonicalUrl: packageJSON.homepage,
Предлагаю отказаться от `type` и `canonicalUrl` и вынести их в компоненту или сайт если они везде одинаковые.

2022-08-06 06:25 UTC, AlecCross commented on src/data/metaTagsData.js
> +const brandsKeywords = categoriesData.categories.brands.subcategories.map(subcategory => subcategory.name).join()
На счет первого:
Слова разделяются запятой. Они нигде не показываются явно и являются тегами для поисковика.

2022-08-06 07:43 UTC, AlecCross commented on src/data/metaTagsData.js
> +const brandsKeywords = categoriesData.categories.brands.subcategories.map(subcategory => subcategory.name).join()
На счет 2го:
Обнаружил что metaTag "keywords" принимает массив строк. Так что можно вообще отказаться от ".join()"

2022-08-07 10:40 UTC, lifearoundfreaks approved these changes

2022-08-07 10:40 UTC, merged